### ISSUE TITLE
Incomplete output when running Docker on 6 fastq

### ISSUE THREAD

**Issue by AdrianParrilla** [thachnguyen/mitopore_workflow#1]
Hi,

I tried running the Docker command:

`docker run -v /mnt/smb/TDA/mtDNA_docker/jurkat7:/mitopore_data/ -i thachdt4/mitopore_local:latest python /home/ag-rossi/projects/mitopore_workflow/mitopore_local/mitopore_snv.py
`
on a fastq folder containing 6 fastaq

<img width="212" alt="input_fastq" src="https://github.com/user-attachments/assets/e5fa1c42-7e5d-4257-b063-8c09de71e952" />

However, the process fails to provide the complete output

<img width="315" alt="output_issue" src="https://github.com/user-attachments/assets/2e552580-6612-4543-ad7b-8c0dc89ca0b9" />

and showing this error message:

[M::main] CMD: minimap2 -t 4 -ax map-ont --secondary=no /home/ag-rossi/projects/mitopore_workflow/mitopore_local/reference/mtDNA/rCRS_shifted.fasta /mitopore_data/fastq/J7.SEV.5Gy.markdup.sorted.fastq
[M::main] Real time: 91.921 sec; CPU: 280.178 sec; Peak RSS: 3.414 GB
[bam_sort_core] merging from 4 files and 1 in-memory blocks...

mtDNA Variant Detection v2.0.0-rc13
https://github.com/seppinho/mutserve
(c) Sebastian Schoenherr, Hansi Weissensteiner, Lukas Forer
[call, /mitopore_data/Analysis/Minimap/J7.bam, --reference, reference/rCRS.fasta, --output, result1.vcf, --threads, 4, --baseQ, 10, --level, 0.05]
  ✔️  J7.bam[----------->--------------------------][00:02:52]
  ✔️  Merge output files

Execution Time: 2 min, 52 sec

mtDNA Variant Detection v2.0.0-rc13
https://github.com/seppinho/mutserve
(c) Sebastian Schoenherr, Hansi Weissensteiner, Lukas Forer
[call, /mitopore_data/Analysis/Minimap/shifted/J7.bam, --reference, /home/ag-rossi/projects/mitopore_workflow/mitopore_local/reference/mtDNA/rCRS_shifted.fasta, --output, result1_shifted.vcf, --threads, 4, --baseQ, 10, --level, 0.05]
  ✔️  J7.bam[------------------------------------>-][00:02:50]
  ✔️  Merge output files

Execution Time: 2 min, 51 sec

[E::bcf_hdr_subset] Duplicate sample name "J7.bam"
Error occurred while subsetting samples
minimap2 -t 4 -ax map-ont --secondary=no *** ./reference/Homo_sapiens.GRCh38.dna.chromosome.MT.fa /mitopore_data/fastq/J7.SEV.Ctrl.markdup.sorted.fastq | samtools view -Sb | samtools sort - -o /mitopore_data/Analysis/Minimap/J7.bam
Run depth calculation for J7.SEV.Ctrl.markdup.sorted.fastq
minimap2 -t 4 -ax map-ont --secondary=no *** ./reference/Homo_sapiens.GRCh38.dna.chromosome.MT.fa /mitopore_data/fastq/J7.LEV.2Gy.markdup.sorted.fastq | samtools view -Sb | samtools sort - -o /mitopore_data/Analysis/Minimap/J7.bam
Run depth calculation for J7.LEV.2Gy.markdup.sorted.fastq
minimap2 -t 4 -ax map-ont --secondary=no *** ./reference/Homo_sapiens.GRCh38.dna.chromosome.MT.fa /mitopore_data/fastq/J7.LEV.5Gy.markdup.sorted.fastq | samtools view -Sb | samtools sort - -o /mitopore_data/Analysis/Minimap/J7.bam
Run depth calculation for J7.LEV.5Gy.markdup.sorted.fastq
minimap2 -t 4 -ax map-ont --secondary=no *** ./reference/Homo_sapiens.GRCh38.dna.chromosome.MT.fa /mitopore_data/fastq/J7.LEV.Ctrl.markdup.sorted.fastq | samtools view -Sb | samtools sort - -o /mitopore_data/Analysis/Minimap/J7.bam
Run depth calculation for J7.LEV.Ctrl.markdup.sorted.fastq
minimap2 -t 4 -ax map-ont --secondary=no *** ./reference/Homo_sapiens.GRCh38.dna.chromosome.MT.fa /mitopore_data/fastq/J7.SEV.2Gy.markdup.sorted.fastq | samtools view -Sb | samtools sort - -o /mitopore_data/Analysis/Minimap/J7.bam
Run depth calculation for J7.SEV.2Gy.markdup.sorted.fastq
minimap2 -t 4 -ax map-ont --secondary=no *** ./reference/Homo_sapiens.GRCh38.dna.chromosome.MT.fa /mitopore_data/fastq/J7.SEV.5Gy.markdup.sorted.fastq | samtools view -Sb | samtools sort - -o /mitopore_data/Analysis/Minimap/J7.bam
Run depth calculation for J7.SEV.5Gy.markdup.sorted.fastq
Traceback (most recent call last):
  File "/home/ag-rossi/projects/mitopore_workflow/mitopore_local/mitopore_snv.py", line 31, in <module>
    main()
  File "/home/ag-rossi/projects/mitopore_workflow/mitopore_local/mitopore_snv.py", line 18, in main
    run_mutserver(path=path1)
  File "/home/ag-rossi/projects/mitopore_workflow/mitopore_local/apps.py", line 215, in run_mutserver
    df = pd.read_csv('%s/Analysis/Results/final_output_2percent.vcf'%path, delimiter='\t', skiprows=11)
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
 
--------------------------------------------------------------------------------------------

I also tried it before with only one sample and it worked nicely.

I hope you can help me to fix the issue,

Best,
Adrian

**Comment by AdrianParrilla** [comment]
I renamed the samples 1-6 and now the issue is solved

**Comment by thachnguyen** [comment]
Thank you for that, that bug is from samples name :)Best regards Thach Nguyen On 17. Dec 2024, at 13:46, Adrian Parrilla ***@***.***> wrote:﻿
I renamed the samples 1-6 and now the issue is solved
